### ISSUE TITLE
Різний результат у shevchenko-js та shevchenko-http для імені "Артем" у кличному відмінку.

### ISSUE THREAD

**Issue by shapovalovei** [tooleks/shevchenko-http#3]
Наразі shevchenko-http у кличному відмінку для імені "Артем" повертає "Артему", а shevchenko-js повертає "Артеме". Правильним варіантом є "Артеме".

Чи не могли б ви оновити код shevchenko-http, щоб він повертав так само, як shevchenko-js?
![photo_2024-04-11 12 45 09](https://github.com/tooleks/shevchenko-http/assets/8914951/e4514c12-62eb-4a8f-be89-4cc80af0b27d)
![photo_2024-04-11 12 45 06](https://github.com/tooleks/shevchenko-http/assets/8914951/faa46cb5-f30e-4e11-9a4c-6407763197f2)

**Comment by tooleks** [comment]
Виправив. Після оновлення запустіть `docker-compose up --build`.
